export class Constant{
  static readonly URL_LIST_MODELS:string = 'https://api.openai.com/v1/models'
  static readonly URL_RETRIEVE_MODEL:string = 'https://api.openai.com/v1/models/'
  static readonly URL_COMPLETIONS:string = 'https://api.openai.com/v1/completions'
  static readonly URL_CHAT_COMPLETION:string = 'https://api.openai.com/v1/chat/completions'
  static readonly URL_COMPLETION:string = 'https://api.openai.com/v1/completions'
  static readonly URL_CREATE_IMAGE:string = 'https://api.openai.com/v1/images/generations'
  static readonly URL_CREATE_IMAGE_EDIT:string = 'https://api.openai.com/v1/images/edits'
  static readonly URL_CREATE_IMAGE_VARIATION:string = 'https://api.openai.com/v1/images/variations'
  static readonly URL_CREATE_TRANSCRIPTION:string = 'https://api.openai.com/v1/audio/transcriptions'
  static readonly URL_CREATE_TRANSLATION:string = 'https://api.openai.com/v1/audio/translations'
  static readonly URL_FINE_TUNE:string = 'https://api.openai.com/v1/fine-tunes'
  static readonly LIST_FINE_TUNE_EVENTS:string = 'events'

  static readonly URL_LIST_FILES:string = 'https://api.openai.com/v1/files'

  static readonly URL_CREATE_MODERATION:string = 'https://api.openai.com/v1/moderations'

  static readonly URL_CREATE_EMBEDDINGS:string =  'https://api.openai.com/v1/embeddings'
}